name: CI build and run
on: [push]
jobs:
  configure:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'

      - name: run
        run: ./build.sh; ./run.sh;


