on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Hello world action step
        id: hello
        uses: actions/LCQPow_actions@v1
      - name: Get the output time
        run: ./build.sh        
