name: Build & Test (ubuntu)

on:
  push:
    branches-ignore:
      - 'main'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'true'
    - name: install pre-reqs
      run: sudo apt-get install -y build-essential cmake libeigen3-dev python3-dev
    - name: build step
      run: mkdir build; cd build; cmake -DBUILD_PYTHON_INTERFACE=OFF ..; make;
    - name: run tests
      run: sh test.sh
