name: CI build and run
on: [push]
jobs:
  build-and-run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - run: make dependencies
      - run: make
      - run: export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$(pwd)/lib; echo $LD_LIBRARY_PATH; bin/warm_up

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - run: mkdir build; cd build; cmake ..; make; ./RunUnitTests