name: Build & Test (macos)

on: 
  push:
    branches-ignore:
      - 'main'      

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: install pre-reqs
      run: brew install cmake
    - name: build step
      run: mkdir build; cd build; cmake -DBUILD_PYTHON_INTERFACE=OFF -DCMAKE_CXX_COMPILER=$(brew --prefix llvm)/bin/clang++..; make;
    - name: run tests
      run: sh test.sh
