name: Build & Test (ubuntu)

on: 
  push:
    branches-ignore:
      - 'main'      

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: install pre-reqs
      run: brew install cmake
    - name: build step
      run: mkdir build; cd build; cmake -DBUILD_PYTHON_INTERFACE=OFF ..; make;
    - name: run tests
      run: sh test.sh
