name: CI build and run
on: [push]
jobs:
  configure:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: install-depends
        run: sudo apt-get install doxygen

      - name: configure
        run: ./configure.sh;

      - name: build
        run: ./configure.sh; ./build.sh

      - name: run
        run: ./configure.sh; ./build.sh; ./run.sh
