on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: LCQP Build Job
    steps:
      - name: Build action step
        id: build
        uses: hallfjonas/LCQPow_actions@master
        with:
          args: --workdir /LCQPow
