name: Build & Test (macos)

on: 
  push:
    branches-ignore:
      - 'main'      

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: install pre-reqs
      run: brew install gcc cmake
    - name: build step
      run: mkdir build; cd build; CXX="gcc-11" CC="gcc-11" cmake -DBUILD_PYTHON_INTERFACE=OFF -DCMAKE_C_COMPILER=/usr/bin/gcc -DCMAKE_CXX_COMPILER=/usr/bin/g++ ..; make;
    - name: run tests
      run: sh test.sh
