name: CI build and run
on: [push]
jobs:
  configure:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: run
        run: echo "Not building or running right now..."; #./build.sh release OFF; ./run.sh
