name: CI build and run
on: [push]
jobs:
  configure:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: ./configure.sh

  build:
    needs: configure
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: ./configure.sh; ./build.sh

  run:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: ./configure.sh; ./build.sh; ./run.sh