name: CI build and run
on: [push]
jobs:
  config-build-test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: configure
        run: ./configure.sh

      - name: build
        run: ./build.sh

      - name: run
        run: ./run.sh