name: Build & Test (ubuntu)

on:
  push:
    branches:
      - 'improve-python-installation'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: install pre-reqs
      run: sudo apt-get install -y build-essential cmake
    - name: build step
      run: mkdir build; cd build; cmake ..; make;
    - name: run tests
      run: sh test.sh